# Generated by Django 5.0 on 2024-09-10 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog_auth", "0002_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="AvatarModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("image", models.ImageField(upload_to="static/avatar")),
            ],
        ),
        migrations.DeleteModel(
            name="User",
        ),
    ]
