# Generated by Django 5.0 on 2024-09-07 09:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BlogCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, verbose_name="category name"),
                ),
            ],
            options={
                "verbose_name": "博客分类",
                "verbose_name_plural": "博客分类",
            },
        ),
        migrations.CreateModel(
            name="Blog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="title")),
                (
                    "description",
                    models.CharField(max_length=268, verbose_name="description"),
                ),
                ("content", models.TextField(verbose_name="content")),
                (
                    "pub_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="pub_time"),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="author",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="blog.blogcategory",
                        verbose_name="category",
                    ),
                ),
            ],
            options={
                "verbose_name": "博客",
                "verbose_name_plural": "博客",
                "ordering": ["-pub_time"],
            },
        ),
        migrations.CreateModel(
            name="BlogComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.CharField(max_length=1000, verbose_name="content")),
                (
                    "pub_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="pub_time"),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="author",
                    ),
                ),
                (
                    "blog",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="blog.blog",
                        verbose_name="blog",
                    ),
                ),
            ],
            options={
                "verbose_name": "博客评论",
                "verbose_name_plural": "博客评论",
                "ordering": ["-pub_time"],
            },
        ),
    ]
